### ISSUE TITLE
Config values differ from auth0 example

### ISSUE THREAD

**Issue by evilpacket** [iceddev/hapi-auth-auth0-lock-webapp#3]
The config values you verify against for the options differ from those provided by auth0. This can lead to some confusion so consistency there might be good, if not documenting the differences might be best.

The values that differ are 

| Auth0 | auth0-lock-webapp |
| --- | --- |
| clientID | clientId |
| callbackURL | redirectUri |

Additionally `clientSecret` can't be restricted to `token()`  because secrets can include - (dash) and token only does alpha numeric and underscore.

`clientSecret: joi.string().token().required()`

I'm happy to provide a PR just wanted to know your thoughts on both issues before I put in the time :)

**Comment by phated** [comment]
@evilpacket great insights.  I think we should support both property names with the Auth0 versions taking precedence; it was in my initial plan but I figured no one would ever use this since our use case was pretty narrow :stuck_out_tongue: 

Interesting note about the `clientSecret`.  I just assumed that they could only be a `token()` because ours looks like that.  I'm fine making that validation more generic.

**Comment by evilpacket** [comment]
Sounds great. Thanks for the comments. I'm using Auth0 for a project with hapi and you wrote the only implementation for a traditional webapp so I went with it. :) Worked pretty drop in. I'll provide docs as I get things working and situated too if we end up using it for the project.

thx for making this. I'll see what I can do to throw together a pr.
